export const GET_USER_ACTIVITY = 'Dashboard/GET_USER_ACTIVITY';
export const SET_USER_ACTIVITY = 'Dashboard/SET_USER_ACTIVITY';
export const GET_USER_CALORIES_CONSUMED = 'Dashboard/GET_USER_CALORIES_CONSUMED';
export const SET_USER_CALORIES_CONSUMED = 'Dashboard/SET_USER_CALORIES_CONSUMED';
