export const GET_ALL_USERS = 'Admin/GET_ALL_USERS';
export const SET_ALL_USERS = 'Admin/SET_ALL_USERS';
export const DELETE_USER_BY_ID = 'DELETE_USER_BY_ID';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const GET_USER_DEMOGRAPHICS = 'GET_USER_DEMOGRAPHICS';
export const SET_USER_DEMOGRAPHICS = 'SET_USER_DEMOGRAPHICS';
export const GET_USER_SEX_DISTRIBUTION = 'GET_USER_SEX_DISTRIBUTION';
export const SET_USER_SEX_DISTRIBUTION = 'SET_USER_SEX_DISTRIBUTION';
